filebeat.inputs:
- type: log
  paths:
    - /logs/*.log

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "s3creT"

setup.kibana:
  host: "kibana:5601"

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
