metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:
  host: "kibana:5601"
  username: "elastic"
  password: "s3creT"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "s3creT"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
